# Importing the Important Libraries

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

# Understanding the dataset

In [2]:
df = pd.read_excel("Dataset for Data Analytics.xlsx")

In [3]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
import io
buf = io.StringIO()
df.info(buf=buf)
s = buf.getvalue()
lines = [line.split() for line in s.splitlines()[3:-2]]
info = pd.DataFrame(lines)
info.columns = info.iloc[0]
info

0     #           Column        Non-Null     Count           Dtype
0     #           Column        Non-Null     Count           Dtype
1   ---           ------  --------------     -----            None
2     0          OrderID            1200  non-null          object
3     1             Date            1200  non-null  datetime64[ns]
4     2       CustomerID            1200  non-null          object
5     3          Product            1200  non-null          object
6     4         Quantity            1200  non-null           int64
7     5        UnitPrice            1200  non-null         float64
8     6  ShippingAddress            1200  non-null          object
9     7    PaymentMethod            1200  non-null          object
10    8      OrderStatus            1200  non-null          object
11    9   TrackingNumber            1200  non-null          object
12   10      ItemsInCart            1200  non-null           int64
13   11       CouponCode             891  non-null          object
14   12   ReferralSource            1200  non-null          object
15   13       TotalPrice            1200  non-null         float64

In [5]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

# Start cleaning steps
### Remove Unused columns

In [6]:
print("The number of unique orders is:", df['OrderID'].nunique()) # Check if the customer has multiple orders.
# This will be useful for customer segmentation and understanding customer behavior.
# But here we can see that each order has a unique OrderID, so we can use OrderID as a unique identifier for each transaction.
# This means that this feature isn't useful so we will drop it
df.drop('OrderID', axis=1, inplace=True)

The number of unique orders is: 1200

In [7]:
print("The number of unique customers is:", df['CustomerID'].nunique()) # Check how many unique customers we have in the dataset. 
# The number of customers is very high on the data 
# This means that we have a lot of customers with only one order, which makes it impossible to do customer segmentation and understanding customer behavior.
# We will drop this feature as well because it won't be useful for our analysis.
df.drop('CustomerID', axis=1, inplace=True)

The number of unique customers is: 1189

In [8]:
print("The number of unique tracking numbers is:", df['TrackingNumber'].nunique()) # Check how many unique tracking numbers we have in the dataset.
# This number is very high so it is not useful for our analysis and we will drop it as well.
df.drop('TrackingNumber', axis=1, inplace=True)

The number of unique tracking numbers is: 1200

In [9]:
print ("The number of unique coupon codes is:",df['CouponCode'].nunique(), end="\n\n") # Check how many unique coupon codes we have in the dataset.
print ("The distrbution of coupon codes is:") # Check the distribution of the coupon codes in the dataset.
pd.DataFrame(df['CouponCode'].value_counts()) # Check the distribution of the coupon codes in the dataset.

The number of unique coupon codes is: 3

The distrbution of coupon codes is:

            count
CouponCode
FREESHIP      313
WINTER15      292
SAVE10        286

In [10]:
print ("The number of shipping address is:", df['ShippingAddress'].nunique(), end="\n\n")
print ("The distribution of the shipping address is:")
pd.DataFrame(df['ShippingAddress'].value_counts(sort=True))
# I will let it may I extract some features

The number of shipping address is: 655

The distribution of the shipping address is:

                 count
ShippingAddress
533 Main St          8
895 Main St          6
146 Main St          5
562 Main St          5
636 Main St          5
...                ...
520 Main St          1
459 Main St          1
539 Main St          1
556 Main St          1
201 Main St          1

[655 rows x 1 columns]

# Check data after removing columns

In [11]:
df.head()

,Date,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,2023-01-04,Monitor,5,570.62,928 Main St,Debit Card,Shipped,7,SAVE10,Instagram,2853.10
1,2024-08-23,Phone,2,151.35,823 Main St,Online,Shipped,3,SAVE10,Referral,302.70
2,2024-02-27,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,8,FREESHIP,Email,2753.40
3,2023-10-15,Chair,1,273.19,275 Main St,Debit Card,Returned,5,SAVE10,Facebook,273.19
4,2025-05-08,Printer,4,626.01,668 Main St,Online,Delivered,8,SAVE10,Email,2504.04

In [12]:
import io
buf = io.StringIO()
df.info(buf=buf)
s = buf.getvalue()
lines = [line.split() for line in s.splitlines()[3:-2]]
info = pd.DataFrame(lines)
info.columns = info.iloc[0]
info

0     #           Column        Non-Null     Count           Dtype
0     #           Column        Non-Null     Count           Dtype
1   ---           ------  --------------     -----            None
2     0             Date            1200  non-null  datetime64[ns]
3     1          Product            1200  non-null          object
4     2         Quantity            1200  non-null           int64
5     3        UnitPrice            1200  non-null         float64
6     4  ShippingAddress            1200  non-null          object
7     5    PaymentMethod            1200  non-null          object
8     6      OrderStatus            1200  non-null          object
9     7      ItemsInCart            1200  non-null           int64
10    8       CouponCode             891  non-null          object
11    9   ReferralSource            1200  non-null          object
12   10       TotalPrice            1200  non-null         float64

# Fill missing values

In [13]:
df['CouponCode'].fillna('No Coupon', inplace=True) # Fill the missing values in the CouponCode column with 'No Coupon' because it is a categorical feature and it is better to fill it with a string rather than a number.

#### Data distribtion of coupon code

In [16]:
pd.DataFrame(df['CouponCode'].value_counts())

            count
CouponCode
FREESHIP      313
No Coupon     309
WINTER15      292
SAVE10        286

# Saving the DataFrame

In [17]:
print ("The data saved successfully in the file 'EDA_Cleaned_Dataset.xlsx'")
df.to_excel("EDA_Cleaned_Dataset.xlsx", index=False)

The data saved successfully in the file 'EDA_Cleaned_Dataset.xlsx'